config/routes.rb
  Rails.application.routes.draw do
  get 'gym/index'

  get 'salon/index'

  get 'restaurants/index'

  get 'result/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'home/index'
  
  devise_for :users ,:controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
  get '/users/sign_in' => 'devise/sessions#new'
  get '/users/sign_out' => 'devise/sessions#destroy'
    
end
resources :users  do
  resources :write_review  
  
    member do
      get :following, :followers
    end
  end
resources :featured_images
resources :relationships  
resources :locations , :defaults => {:format => "json"}
get '/location.json' => 'home#index', :defaults => {:format => 'json'}
get '/resultlocation.json' => 'result#index', :defaults => {:format => 'json'}
get '/review.json' => 'result#reviewdetails', :defaults => {:format => 'json'}
get '/userreviews.json' => 'relationships#index', :defaults => {:format => 'json'}
get '/likes.json' => 'result#like', :defaults => {:format => 'json'}
get '/dislikes.json' => 'result#dislike', :defaults => {:format => 'json'}
get '/pgresults.json' => 'result#pgresult', :defaults => {:format => 'json'}
get '/pgresultsbyfood.json' => 'result#pgresultbyfoodtype', :defaults => {:format => 'json'}
get '/restaurantresults.json' => 'restaurants#restaurantresult', :defaults => {:format => 'json'}
get 'relationships/show' 
get '/salonresults.json' => 'salon#salonresult', :defaults => {:format => 'json'}
   root 'home#index'
    post '/create' => 'home#create' 
    

   match '/phonenum' => 'home#phonenum', :via => 'get'
   match '/result' => 'result#index', :via => 'get'
   
   
   get '/review' => 'result#completereview'
   match '/writereview' => 'result#write_review', :via => 'get'
   match '/restaurants' => 'restaurants#index', :via => 'get'
    post '/createreview' => 'result#create' 
    post '/createrestreview' => 'restaurants#create'
    get '/like/:id' => 'result#like' ,as: 'like'
    get '/dislike/:id' => 'result#dislike' ,as: 'dislike'
    post '/createfollower' => 'relationships#create'
    delete '/deletefollower' => 'relationships#destroy'
  match '/followuser' => 'relationships#show', :via => 'get'
  match '/details' => 'detail#details', :via => 'get'
  match '/restaurant_details' => 'restaurant_detail#restaurant_details', :via => 'get'
  match '/salon' => 'salon#index', :via => 'get'
  match '/salon_details' => 'salon_detail#salon_details', :via => 'get'
  match '/gym' => 'gym#index', :via => 'get'
  match '/writerestaurantreview' => 'restaurants#restwritereview', :via => 'get'

end

app/controllers/result_controller.rb
class ResultController < ApplicationController
  def index()
  	@locations  = Location.where('name LIKE ?', "%#{params[:address]}%")
    respond_to do |format|
    format.html
    format.json { render json: @locations }
    @search_results = SearchResult.all
    
  end
  end
  def pgresult
    @pgresults = []
   wrev = {} 
   wrev["wrev"] = ""
  wrev["wrev"]  = SearchResult.all
   @pgresults << wrev
       wrev = {}
    respond_to do |format|
    format.html
    format.json { render json: @pgresults }
  end
  end  
  def pgresultbyfoodtype
   @pgresults = []
   wrev = {} 
   wrev["wrev"] = ""
   wrev["meal"] = ""
   wrev["sharing"] = ""
   query_string = String.new
   query_values = []
   
     if  params[:sharing_type].nil? and params[:filter_type].nil?
         wrev["wrev"]  = SearchResult.all
         @pgresults << wrev
         wrev = {}
         
     end

     if params[:sharing_type]  != nil and params[:filter_type].nil?
      params[:sharing_type].each do |sharing_type|
       wrev["wrev"]  = SearchResult.by_sharingtype( sharing_type) 
       @pgresults << wrev
       wrev = {}
     end
      end
       
    if params[:filter_type] != nil and params[:sharing_type]  != nil
    params[:filter_type].each do |filter_type|
        if filter_type == "desending"
     params[:sharing_type].each do |sharing_type|
        wrev["wrev"]  = SearchResult.by_sharingtype( sharing_type).order("price desc")
        @pgresults << wrev
        wrev = {}
       end 
       else
       params[:sharing_type].each do |sharing_type|
      wrev["wrev"]  = SearchResult.by_sharingtype( sharing_type) 
       @pgresults << wrev
       wrev = {}
     end
  end
      if params[:sharing_type].nil? and params[:filter_type] != nil
        params[:filter_type].each do |filter_type|
        if filter_type == "desending"
         wrev["wrev"]  = SearchResult.order("price desc")
         @pgresults << wrev
        wrev = {}
        end
      end
      end

end
end
    respond_to do |format|
    format.html
    format.json { render json: @pgresults }
  end
  end
  def new
  end 
  def details
    @user = User.new

  end
  def reviewdetails
    @users = User.all
   @total = [] #each element of this array would contain a hash of _'user, reviews[]'_
wrev = {}  # a hash that will contain the user, and its write reviews
wrev["user"] = ""
wrev["email"] = ""
wrev["followers"] = 0
wrev["user_images"] = ""
wrev["wrev"] = "" #reviews are an array 
wrev["likes"] = 0
@likes = WriteReview.new
@users.each do |u|
 wrev["user"] = u.username
 wrev["email"] = u.email
 wrev["followers"] = u.followers.count
 wrev["user_images"] = u.user_images

 wrev["wrev"] = u.write_reviews.last
 @likes = u.write_reviews.all
 @likes.each do |h|
  wrev["likes"] = h.get_likes.size
  wrev["dislikes"] = h.get_dislikes.size
 end
 
 @total << wrev 
 wrev = {}
end

respond_to do |format|
 format.html
 format.json { render json: @total }
end
  
  end
  def completereview
  end
  def write_review
  	@writereview = WriteReview.new
  end
  def create 
     @writereview = WriteReview.new(user_params)

   if @writereview.save!
   redirect_to root_path
  end
   end
 def like
@writereview = WriteReview.find(params[:id])
@writereview.liked_by current_user
  Notification.create(
             write_review_id: @writereview.id,
            user_id: current_user.id,
             read: false,
             text: (current_user.username + " likes you comment")
              )

      @users = User.all
   @total = [] #each element of this array would contain a hash of _'user, reviews[]'_
wrev = {}  # a hash that will contain the user, and its write reviews
wrev["user"] = ""
wrev["email"] = ""
wrev["followers"] = 0
wrev["user_images"] = ""
wrev["wrev"] = "" #reviews are an array 
wrev["likes"] = 0
@likes = WriteReview.new
@users.each do |u|
 wrev["user"] = u.username
 wrev["email"] = u.email
 wrev["followers"] = u.followers.count
 wrev["user_images"] = u.user_images

 wrev["wrev"] = u.write_reviews.last
 @likes = u.write_reviews.all
 @likes.each do |h|
  wrev["likes"] = h.get_likes.size
  wrev["dislikes"] = h.get_dislikes.size
 end
 
 @total << wrev 
 wrev = {}
end

respond_to do |format|
 format.html
 format.json { render json: @total }
end 
    
end

def dislike
@writereview = WriteReview.find(params[:id])
@writereview.disliked_by current_user
Notification.create(
             write_review_id: @writereview.id,
            user_id: current_user.id,
             read: false,
             text: (current_user.username + " dislikes you comment")
              )
 @users = User.all
    @total = [] #each element of this array would contain a hash of _'user, reviews[]'_
wrev = {}  # a hash that will contain the user, and its write reviews
wrev["user"] = ""
wrev["email"] = ""
wrev["followers"] = 0
wrev["user_images"] = ""
wrev["wrev"] = "" #reviews are an array 
wrev["likes"] = 0
@likes = WriteReview.new
@users.each do |u|
 wrev["user"] = u.username
 wrev["email"] = u.email
 wrev["followers"] = u.followers.count
 wrev["user_images"] = u.user_images

 wrev["wrev"] = u.write_reviews.last
 @likes = u.write_reviews.all
 @likes.each do |h|
  wrev["likes"] = h.get_likes.size
  wrev["dislikes"] = h.get_dislikes.size
 end
 
 @total << wrev 
 wrev = {}
end

respond_to do |format|
 format.html
 format.json { render json: @total }
end
end

   private
  
    def user_params
       params.require(:write_review).permit(:clean,:food,:locality,:behavior,:amenity,:likes,:dislikes,:comment,:user_id)
    end 
end

app/helpers/result_helper.rb
module ResultHelper
end

app/views/result/details.html.erb
<div class="container">	
	<div class="col-md-12">
		<h3>Sharing PG for Ladies</h3>
		<div class="col-md-7 no-padding">
			<div class="col-md-12 no-padding">
				<div class="col-md-4" style="padding-right:5px;padding-left:5px;">
					<%=image_tag ("featured-1.jpg"), :class=>"img-responsive" %>
				</div>
				<div class="col-md-4" style="padding-right:5px;padding-left:5px;">
					<%=image_tag ("featured-2.jpg"), :class=>"img-responsive" %>
				</div>
				<div class="col-md-4" style="padding-right:5px;padding-left:5px;">
					<%=image_tag ("featured-2.jpg"), :class=>"img-responsive" %>
				</div>
			</div>
			<a id="modal-876258" href="#modal-container-876258" role="button" class="btn" data-toggle="modal" data-target=".pg-modal-lg">Show more Photos&nbsp;<i class="fa fa-angle-right"></i><i class="fa fa-angle-right"></i></a>
			<h4>Description</h4>
			<p class="pg-description">The PG belongs to sukumar and is located in BTM Layout, 8, Outer Ring Rd, KEB Colony, Stage 1, Bengaluru, Karnataka 560029, India. This Paying Guest is available for Student, Working on Sharing basis. The PG comes with all the needful amenities such as WIFI, Washing Machine, Television, Geyser, Bed, Cupboard, Fan, Modular Kitchen, Western Toilet. Parking, 24 Hours Water Supply, Power Backup are the other services that the PG residents can avail. There are certain guidelines for the paying guests such as Entry Time 12:00 AM. The rent of the PG is Rs.4,500 and Deposit is Rs.2,000</p>
			<div class="col-md-12 no-padding" ng-controller="filterPgController">
				<div class="col-md-4" style="padding-left:0;">
					<h4>PG Amenities</h4>
					<ul ng-repeat="amenity in filteredPg" class="amenities list-unstyled" id="amenity">
						<li>{{amenity}}</li>
					</ul>
				</div>
				<div class="col-md-4">
					<h4>PG Services</h4>
					<ul class="services list-unstyled" id="service">
						<li>Security</li>
						<li>Parking</li>
						<li>Lift</li>
						<li>Power Backup</li>
					</ul>
				</div>
				<div class="col-md-4" style="padding-right:0;">	
					<h4>Nearby Places</h4>
					<ul class="nearby list-unstyled" id="nearby">
						<li>Restaurant</li>
						<li>Gym</li>
						<li>Hospital</li>
						<li>Shopping Mall</li>
						<li>ATM</li>
						<li>Transportation</li>
					</ul>
				</div>
			</div>
		</div>
		
		<div class="col-md-4 col-md-offset-1 pg-details-list">
			<div class="pg-name">
				<label>Name of the owner</label>
				<p><%=@pgresults.pgname%></p>
			</div>
			<div class="pg-name">
				<label>Contact owner</label>
				<p><i class="fa fa-phone"></i>&nbsp;<%=@pgresults.phone1%></p>
			</div>
			<div class="address">
				<label>Address</label>
				<p><%=@pgresults.pgadress%></p>
			</div>
			<div class="review-link" id="scrollArea" ng-controller="ScrollCtrl">
				<a href="<%=writereview_path %>" class="write">Write Review</a>
				<a ng-click="gotoElement('review-details')" href="#" class="read">Read Reviews</a>
			</div>			
			<h4>Featured Roofs nearby your location</h4>
			<div class="carousel slide" id="carousel-411046">
				<ol class="carousel-indicators">
					<li class="active" data-slide-to="0" data-target="#carousel-411046">
					</li>
					<li data-slide-to="1" data-target="#carousel-411046">
					</li>
					<li data-slide-to="2" data-target="#carousel-411046">
					</li>
				</ol>
				<div class="carousel-inner">
					<div class="item active">
						<%=image_tag ('featured-2.jpg'),:class=>"img-responsive",:style=>"width:100%;height:250px;" %>
						<div class="carousel-caption">
							<h4>
								Sai Baba Pg
							</h4>
							<p>
								House No. 34, Balaji Layout, Bellandur Gate,Sarjapura Road, Bangalore,India
							</p>
						</div>
					</div>
					<div class="item">
						<%=image_tag ('featured-1.jpg'),:class=>"img-responsive",:style=>"width:100%;height:250px;" %>
						<div class="carousel-caption">
							<h4>
								Sai Baba Pg
							</h4>
							<p>
								House No. 34, Balaji Layout, Bellandur Gate,Sarjapura Road, Bangalore,India
							</p>
						</div>
					</div>
					<div class="item">
						<%=image_tag ('featured-3.jpg'),:class=>"img-responsive",:style=>"width:100%;height:250px;" %>
						<div class="carousel-caption">
							<h4>
								Sai Baba Pg
							</h4>
							<p>
								House No. 34, Balaji Layout, Bellandur Gate,Sarjapura Road, Bangalore,India
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		
		<div class="clearfix"></div>
	</div>
</div>	
<div class="container review" ng-controller="reviewController">
 	<h3>Reviews by the User</h3>
 	<div class="col-md-12 review-wrapper" ng-repeat="reviewDetail in reviewDetails | limitTo:quantity" id="review-details">
 		<div class="col-md-1">
 			<img ng-src='{{reviewDetail.user_images}}'class="img-responsive"/>
 		</div>
 		
		<div class="col-md-11">
		<p><a href="#" ng-click="gotoFollower(reviewDetail.user)">{{reviewDetail.user}}</a> &nbsp;| Followers ({{reviewDetail.followers}})</p>
 		<p>{{reviewDetail.wrev.likes}}</p>
       
			<a href="#" ng-click="gotolikes(reviewDetail.wrev.id)"><i class="fa fa-thumbs-up"></i>&nbsp;like</a>&nbsp; {{reviewDetail.likes}}
			
            
			<a href="#" ng-click="gotodislikes(reviewDetail.wrev.id)"  style="margin-left:1%;"><i class="fa fa-thumbs-down"></i>&nbsp;Dislike </a>&nbsp; {{reviewDetail.dislikes}}
			<a href="#" style="margin-left:1%;" ng-click="commentbox = ! commentbox"><i class="fa fa-comment"></i>&nbsp;Comment</a>
			<a href="#" style="margin-left:1%;"><i class="fa fa-check"></i>&nbsp;Recommend</a>
			<input type="text" class="form-control" ng-show="commentbox" style="width:32%;margin-top:1%;"/>
		</div>
	</div>
	<a href="<%=review_path%>">More Reviews &nbsp;<i class="fa fa-angle-right"></i><i class="fa fa-angle-right"></i>
</div>		
<div class="modal fade pg-modal-lg" id="modal-container-876258" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				 
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
					X
				</button>
				<h4 class="modal-title" id="myModalLabel">
					More Photos
				</h4>
			</div>
			<div class="col-md-12 modal-body">
				<div class="carousel slide" id="carousel-411046">
					<ol class="carousel-indicators">
						<li class="active" data-slide-to="0" data-target="#carousel-411046">
						</li>
						<li data-slide-to="1" data-target="#carousel-411046">
						</li>
						<li data-slide-to="2" data-target="#carousel-411046">
						</li>
					</ol>
					<div class="carousel-inner">
						<div class="item active">
							<%=image_tag ('featured-2.jpg'),:class=>"img-responsive" %>
						</div>
						<div class="item">
							<%=image_tag ('featured-1.jpg'),:class=>"img-responsive" %>
						</div>
						<div class="item">
							<%=image_tag ('featured-3.jpg'),:class=>"img-responsive" %>
						</div>
					</div>
				</div>
			</div>
			<div class="clearfix"></div>
			<div class="modal-footer">
				<a href="#" class="pull-left" style="font-size:16px;"><strong>Write Review</strong></a>
				<button type="button" class="btn btn-default" data-dismiss="modal">
					Close
				</button> 
			</div>
		</div>
	</div>
</div>

app/views/result/index.html.erb
<div class="col-md-12 search-box" ng-controller="filterController">	
	<form class="form-inline text-center" role="form">
		<div class="form-group inline-form-grp">
		<label for="location">Location:</label>
			<input type="text" class="form-control" data-provide="typeahead" id="name" autocomplete="off" value=location_id>
		</div>
		<div class="form-group inline-form-grp">
			<!-- <label for="location">Gender:</label>
			<select class="form-control">
				<option>
					Male
				</option>
				<option>
					Female
				</option>
			</select> -->
			<label for="location">Gender:</label>
			<select name="gender" ng-model="user.gender" ng-options="gender.id as gender.desc for gender in genders" class="form-control">
				<option value="">Please select one option</option>
			</select>
		</div>
		<div class="form-group inline-form-grp">
			<label for="location">Price Range:</label>
			<select name="range" ng-model="user.range" ng-options="range.id as range.desc for range in ranges" class="form-control">
				<option value="">Please select one option</option>
			</select>
		</div>
		<div class="form-group" style="margin-top:1%;">
			<button type="submit" class="btn" ng-click="searchResult()">Search PG</button>
		</div>
	</form>
</div>
<div class="col-md-12" style="margin-top:3%;margin-bottom:3%;" ng-controller="filterPgController">
    <div class="col-md-2" style="height:100%;"> 
		<div class="col-md-12 col-xs-6"> 
    		<h4>Sort By</h4>       
        	<div ng-repeat="type in sortGroup">
            	<label class="checkbox-inline">
            		<input type="checkbox" ng-model="type.checked" ng-click="getresultbyfood(type.id,type.groupid)"/>{{type.type}}
            	</label>
       	 	</div>
    	</div>
  	
		<div class="col-md-12 col-xs-6"> 
	    	<h4>Sharing</h4>       
	        <div ng-repeat="share in shareGroup">
	            <label class="checkbox-inline">
	           	 	<input type="checkbox" ng-model="share.checked" ng-click="getresultbyfood(share.id,share.groupid)" />{{share.type}}
	           	</label>
	        </div>
	    </div>
    
    	

	    </div>
    
	<div class="col-md-10 pg-details-list" ng-repeat="pgDetail in filteredPg">		
		<div class="col-md-12 col-xs-12 col-sm-6" ng-repeat="pgdetail in pgDetail.wrev">
			<a href="#" ng-click="gotoDetails(pgdetail.id)">
				<div class="col-md-3">
				<!-- <a href="<%=details_path%>" target="_blank"></a>-->
					<%= image_tag ('featured-2.jpg'),:class=>"img-responsive" %>
				</div>
				<h4 class="{{pgdetail.gender}}">Sharing PG For {{pgdetail.gender}}</h4>
				<div class="col-md-6 no-padding">
					<div class="pg-name">
						<label>Name</label>
						<p>{{pgdetail.pgname}}</p>
					</div>
					<div class="address">
						<label>Address</label>
						<p>{{pgdetail.pgadress}}</p>
					</div>
				</div>
				<div class="col-md-3 no-padding">
					<div class="rent pull-left">
						<label>Rent</label>
						<div class="amount">
							<span>{{pgdetail.price}}<sub>per month</sub></span>
						</div>
					</div>
					<div class="deposit pull-right">
						<label>Security Deposit</label>
						<div class="security-amount">
							<span>{{pgdetail.secdeposit}}</span>
						</div>
					</div>
					<div class="clearfix"></div>
					<div class="time">
						<p>{{pgdetail.postdate}}</p>
					</div>
					<div class="review-link">
						<a href="#" class="write">Write Review</a>
						<a href="#" class="read">Read Reviews</a>
					</div>
				</div>
			</a>
		</div>
	</div>
</div>
<div class="clearfix"></div>
<script type="text/javascript">
	$("#owl-suggested-featured").owlCarousel({
	    navigation: true,
	    items: 1,
	    navigationText: [
	      "<i class='fa fa-chevron-left icon-white'></i>",
	      "<i class='fa fa-chevron-right icon-white'></i>"
	      ],
	});
</script>

app/views/result/write_review.html.erb
<div class="container">
	<div class="col-md-8 col-md-offset-2">
		<h3>Rate Your Experience</h3>
		<%= form_for (@writereview), url: createreview_path(@writereview),:class=>"form-horizontal",method: :post ,:html => { :multipart => true } do |f|  %>
		<%= f.hidden_field :user_id, :value => current_user.id %>
		
		
			<div class="form-inline">
				<div class="form-group">
				    <label for="clean">Cleanliness</label>
				    <%= f.select(:clean, [['1', 1], ['1.5', 2], ['2',3],['2.5',4],['3',5],['3.5',6],['4',7],['4.5',8],['5',9]],{},{ :class => "form-control"}) %>
				</div>
				<div class="form-group">
				    <label for="clean">Food</label>
				    <%= f.select(:food, [['1', 1], ['1.5', 2], ['2',3],['2.5',4],['3',5],['3.5',6],['4',7],['4.5',8],['5',9]],{},{ :class => "form-control"}) %>
				</div>
				<div class="form-group">
				    <label for="clean">Locality</label>
				    <%= f.select(:locality, [['1', 1], ['1.5', 2], ['2',3],['2.5',4],['3',5],['3.5',6],['4',7],['4.5',8],['5',9]],{},{ :class => "form-control"}) %>
				</div>
				<div class="form-group">
				    <label for="clean">Owner Behavior</label>
				     <%= f.select(:behavior, [['1', 1], ['1.5', 2], ['2',3],['2.5',4],['3',5],['3.5',6],['4',7],['4.5',8],['5',9]],{},{ :class => "form-control"}) %>
				</div>
				<div class="form-group">
				    <label for="clean">PG Amenities(Eg: WiFi,Fridge,Washing Machine etc.)</label>
				    <%= f.select(:amenity, [['1', 1], ['1.5', 2], ['2',3],['2.5',4],['3',5],['3.5',6],['4',7],['4.5',8],['5',9]],{},{ :class => "form-control"}) %>
				</div>
			</div>
			<div class="form-group">
				<label for="like">
					What do you like about the PG
				</label>
				<%= f.text_area(:likes, rows: 5, :class => 'form-control') %>
			</div>
			<div class="form-group">
				<label for="dislike">
					What do you dislike about the PG
				</label>
				<%= f.text_area(:dislikes, rows: 5, :class => 'form-control') %>
			</div>
			<div class="form-group">
				<label for="comment">
					Additional comments
				</label>
				<%= f.text_area(:comment, rows: 5, :class => 'form-control') %>
			</div>
			<%= f.submit "Submit", :class => "btn btn-primary center-block",:style=>"margin-bottom:3%" %>
		<% end %>
	</div>
</div>