config/routes.rb
  Rails.application.routes.draw do
  get 'gym/index'

  get 'salon/index'

  get 'restaurants/index'

  get 'result/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'home/index'
  
  devise_for :users ,:controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
  get '/users/sign_in' => 'devise/sessions#new'
  get '/users/sign_out' => 'devise/sessions#destroy'
    
end
resources :users  do
  resources :write_review  
  
    member do
      get :following, :followers
    end
  end
resources :featured_images
resources :relationships  
resources :locations , :defaults => {:format => "json"}
get '/location.json' => 'home#index', :defaults => {:format => 'json'}
get '/resultlocation.json' => 'result#index', :defaults => {:format => 'json'}
get '/review.json' => 'result#reviewdetails', :defaults => {:format => 'json'}
get '/userreviews.json' => 'relationships#index', :defaults => {:format => 'json'}
get '/likes.json' => 'result#like', :defaults => {:format => 'json'}
get '/dislikes.json' => 'result#dislike', :defaults => {:format => 'json'}
get '/pgresults.json' => 'result#pgresult', :defaults => {:format => 'json'}
get '/pgresultsbyfood.json' => 'result#pgresultbyfoodtype', :defaults => {:format => 'json'}
get '/restaurantresults.json' => 'restaurants#restaurantresult', :defaults => {:format => 'json'}
get 'relationships/show' 
get '/salonresults.json' => 'salon#salonresult', :defaults => {:format => 'json'}
   root 'home#index'
    post '/create' => 'home#create' 
    

   match '/phonenum' => 'home#phonenum', :via => 'get'
   match '/result' => 'result#index', :via => 'get'
   
   
   get '/review' => 'result#completereview'
   match '/writereview' => 'result#write_review', :via => 'get'
   match '/restaurants' => 'restaurants#index', :via => 'get'
    post '/createreview' => 'result#create' 
    post '/createrestreview' => 'restaurants#create'
    get '/like/:id' => 'result#like' ,as: 'like'
    get '/dislike/:id' => 'result#dislike' ,as: 'dislike'
    post '/createfollower' => 'relationships#create'
    delete '/deletefollower' => 'relationships#destroy'
  match '/followuser' => 'relationships#show', :via => 'get'
  match '/details' => 'detail#details', :via => 'get'
  match '/restaurant_details' => 'restaurant_detail#restaurant_details', :via => 'get'
  match '/salon' => 'salon#index', :via => 'get'
  match '/salon_details' => 'salon_detail#salon_details', :via => 'get'
  match '/gym' => 'gym#index', :via => 'get'
  match '/writerestaurantreview' => 'restaurants#restwritereview', :via => 'get'

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	
	 belongs_to :follower, class_name: "User"
     belongs_to :followed, class_name: "User"

    validates :follower_id, presence: true
    validates :followed_id, presence: true
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	
  def show
    
    @otheruser =  User.find_by_username(params[:name])
    @reviews  =  @otheruser.write_reviews.all
    
    @relationship = Relationship.where(
    follower_id: current_user.id,
    followed_id: @otheruser.id
).first_or_initialize if current_user
    
	end	
  
  
	def create
	   @relationship = Relationship.new
        @relationship.followed_id = params[:followed_id]
        @relationship.follower_id = current_user.id
 
    if @relationship.save
        redirect_to followuser_url(name: params[:name])
    else
        flash[:error] = "Couldn't Follow"
        redirect_to root_url
    end
  end

  def destroy
  	@relationship = Relationship.where(follower_id: current_user.id, id: params[:id]).first_or_initialize
    @relationship.destroy
    
    
    redirect_to followuser_url(name: params[:name])
  end
 
 
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow.html.erb
<%= form_for @relationship do %>
     <%= hidden_field_tag :followed_id, @otheruser.id %>
     <%= hidden_field_tag :name, @otheruser.username %>
     <%= submit_tag "Follow" ,class: "btn btn-primary" %>
 <% end %>

app/views/relationships/_unfollow.html.erb
<%= form_tag relationship_path(@relationship), method: :delete do %>
     <%= hidden_field_tag :name, @otheruser.username %>
    <%= submit_tag "Unfollow" ,class: "btn btn-danger" %>
 <% end %>

app/views/relationships/show.html.erb
<div class="container" style="margin-top:3%;margin-bottom:3%;" ng-controller="FollowerController">
	<div class="col-md-12">
		<div class="col-md-3" ng-repeat="followerProfileDetail in followerProfileDetails">
			<img ng-src="/assets/{{followerProfileDetail.reviewerImage}}" class="img-responsive img-circle">
			<div class="follower-name"><strong><%= @otheruser.username %></strong></div>
			<div class="follower-caption"></div>
			<div class="follower-rating">{{followerProfileDetail.title}}</div>
			<div><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-half"></i></div>
			<% if current_user and @otheruser != current_user %>
			<% if current_user.following?(@otheruser) %>
               <%= render 'unfollow' %>
            <% else %>
               <%= render 'follow' %>
            <% end %>
			<% end %>
			<div class="col-md-12 no-padding">
				<ul class="list-unstyled follower-details" ng-repeat="followerCategory in followerCategories">
					<li><a href rollver ng-click="select(followerCategory)">{{followerCategory}}</a></li>
				</ul>
			</div>
		</div>
		<div class="col-md-7">
			<div class="col-md-12 no-padding" id="review" ng-show="divShow == 'Reviews'">
				<h3>Reviews by the user</h3>
				<div>
					<% @reviews.each do |h| %>
  			          <div class="choice-name">
						<strong><%= h.likes %></strong>
					</div>
					<div class="choice-location">
						<strong><%= h.likes %></strong>
					</div>
					<div class="post-date">
						<strong><%= h.created_at.strftime("Posted on %b %d, %Y") %></strong>
					</div>
					<div class="review">
						<p><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-half"></i></p>
						<p class="text-justify"></p>
					</div>
					<% end %>
				</div>

  			 
			</div>
			<div class="col-md-12 no-padding" id="followers" ng-repeat="followerProfileDetail in followerProfileDetails" ng-show="divShow == 'Followers'">
				<% @otheruser.followers.each do |h| %>
				<div class="col-md-1 no-padding">
					<img ng-src="<%=h.user_images%>" class="img-responsive img-circle">
				</div>
				<div class="col-md-6">
					<div><%= h.username %> | Followers (<%= h.followers.count %>) </div>
					<div> Reviews(<%= h.write_reviews.count %>) | <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-half"></i></div>
				</div>
				<div class="col-md-6">
					<% if current_user and h != current_user  %>
					<% if current_user.followeds?(h) %>
					<button type="button" class="btn btn-danger">Unfollow</button>
					<% else %>
					<button type="button" class="btn btn-primary">Follow</button>
					<% end %>
					<% end %>
				</div>
			</div>
			<% end %>
			<div class="col-md-12" ng-show="divShow == 'Photos'">
				<div class="col-md-4" ng-repeat="photo in photos">
					 <a id="modal-{{photo.image}}" href="#modal-container-{{photo.image}}" role="button" data-toggle="modal"><img ng-src="/assets/{{photo.image}}.jpg" class="img-responsive center-block"style="height:102px;"/></a>
				</div>
			</div>
		</div>
		<div class="col-md-2 no-padding" ng-show= "divShow=='Photos'" ng-repeat="suggestedFollowerProfileDetail in suggestedFollowerProfileDetails">
			<h4>Suggested Followers</h4>
			<div class="col-md-12 no-padding">
				<div>{{suggestedFollowerProfileDetail.reviewer}} | Followers ({{suggestedFollowerProfileDetail.reviewerFollower}})</div>
				<div> Reviews({{suggestedFollowerProfileDetail.reviewsInTotal}}) | <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-half"></i></div>
			</div>
			<div class="col-md-12 no-padding">
				<button type="button" class="btn btn-primary">Follow</button>
			</div>
		</div>
	</div>
	<div class="modal fade" id="modal-container-{{photo.image}}" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" ng-repeat="photo in photos">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						X
					</button>
				</div>
				<div class="modal-body">
					<img ng-src="/assets/{{photo.image}}.jpg" class="img-responsive center-block"/>
					<div class="modal-caption">
						{{photo.caption}}
					</div>
				</div>
			</div>
		</div>
	</div>
</div>