config/routes.rb
  Rails.application.routes.draw do
  get 'gym/index'

  get 'salon/index'

  get 'restaurants/index'

  get 'result/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'home/index'
  
  devise_for :users ,:controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
  get '/users/sign_in' => 'devise/sessions#new'
  get '/users/sign_out' => 'devise/sessions#destroy'
    
end
resources :users  do
  resources :write_review  
  
    member do
      get :following, :followers
    end
  end
resources :featured_images
resources :relationships  
resources :locations , :defaults => {:format => "json"}
get '/location.json' => 'home#index', :defaults => {:format => 'json'}
get '/resultlocation.json' => 'result#index', :defaults => {:format => 'json'}
get '/review.json' => 'result#reviewdetails', :defaults => {:format => 'json'}
get '/userreviews.json' => 'relationships#index', :defaults => {:format => 'json'}
get '/likes.json' => 'result#like', :defaults => {:format => 'json'}
get '/dislikes.json' => 'result#dislike', :defaults => {:format => 'json'}
get '/pgresults.json' => 'result#pgresult', :defaults => {:format => 'json'}
get '/pgresultsbyfood.json' => 'result#pgresultbyfoodtype', :defaults => {:format => 'json'}
get '/restaurantresults.json' => 'restaurants#restaurantresult', :defaults => {:format => 'json'}
get 'relationships/show' 
get '/salonresults.json' => 'salon#salonresult', :defaults => {:format => 'json'}
   root 'home#index'
    post '/create' => 'home#create' 
    

   match '/phonenum' => 'home#phonenum', :via => 'get'
   match '/result' => 'result#index', :via => 'get'
   
   
   get '/review' => 'result#completereview'
   match '/writereview' => 'result#write_review', :via => 'get'
   match '/restaurants' => 'restaurants#index', :via => 'get'
    post '/createreview' => 'result#create' 
    post '/createrestreview' => 'restaurants#create'
    get '/like/:id' => 'result#like' ,as: 'like'
    get '/dislike/:id' => 'result#dislike' ,as: 'dislike'
    post '/createfollower' => 'relationships#create'
    delete '/deletefollower' => 'relationships#destroy'
  match '/followuser' => 'relationships#show', :via => 'get'
  match '/details' => 'detail#details', :via => 'get'
  match '/restaurant_details' => 'restaurant_detail#restaurant_details', :via => 'get'
  match '/salon' => 'salon#index', :via => 'get'
  match '/salon_details' => 'salon_detail#salon_details', :via => 'get'
  match '/gym' => 'gym#index', :via => 'get'
  match '/writerestaurantreview' => 'restaurants#restwritereview', :via => 'get'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	respond_to :json
  def index
  	@featured_images = FeaturedImage.new
  	@featured_images = FeaturedImage.all
    @locations  = Location.all
    respond_to do |format|
    format.html
    format.json { render json: @locations }
  end
  end
  def phonenum
  	@user = User.new
  end
  def create 
  @user = User.find(current_user.id) 
      if @user.update_attributes(user_params)
   redirect_to root_path
  
  end
end
  

  private

  def user_params
        params.require(:user).permit(:phno)
    end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
	<div class="col-md-12 home-bg">
	<div class="col-md-6 side-icon">
		<div class="col-md-2 col-xs-12 icon_placement">
			<%=image_tag 'icon1.png', :class=>'img-responsive' %>
		</div>
		<div class="col-md-4 col-xs-12 no-padding">
			<div class="dialogbox">
			    <div class="body">
			      <span class="tip tip-left"></span>
			      <div class="message">
			        <ul class="descp">
						<li>Some text here</li>
						<li>Some text here</li>
						<li>Some text here</li>
						<li>Some text here</li>
					</ul>
			      </div>
			    </div>
			</div>
		</div>
		<div class="clearfix"></div>
		<div class="col-md-2 col-xs-12 icon_placement">
			<%=image_tag 'icon2.png', :class=>'img-responsive' %>
		</div>
		<div class="col-md-4 col-xs-12 no-padding">
			<div class="dialogbox">
			    <div class="body">
			      <span class="tip tip-left"></span>
			      <div class="message">
			        <ul class="descp">
						<li>Some text here</li>
						<li>Some text here</li>
						<li>Some text here</li>
						<li>Some text here</li>
					</ul>
			      </div>
			    </div>
			</div>
		</div>
		<div class="clearfix"></div>
		<div class="col-md-2 col-xs-12 icon_placement">
			<%=image_tag 'icon3.png', :class=>'img-responsive' %>
		</div>
		<div class="col-md-4 col-xs-12 no-padding">
			<div class="dialogbox">
			    <div class="body">
			      <span class="tip tip-left"></span>
			      <div class="message">
			        <ul class="descp">
						<li>Some text here</li>
						<li>Some text here</li>
						<li>Some text here</li>
						<li>Some text here</li>
					</ul>
			      </div>
			    </div>
			</div>
		</div>
	</div>
</div>
<div class="clearfix"></div>
<div class="container-fluid hideme">
	<div class="row">
		<div class="col-md-12">
			<h3 class="text-center" style="margin-top:5%;">Your Review. Your Choice</h3>
			<div class="tabbable" id="tabs-680206" style="margin-top:2%;">
				<ul class="nav nav-tabs nav-justified">
					<li class="active">
						<a href="#panel-882360" data-toggle="tab">PG</a>
					</li>
					<li>
						<a href="#panel-43018" data-toggle="tab">Nearby You</a>
					</li>
				</ul>
				<div class="tab-content" ng-controller="filterController">
					<div class="tab-pane active" id="panel-882360">
						<form class="form-inline text-center" role="form">
							<div class="form-group inline-form-grp">
								<label for="location">Location:</label>
								<select name="location" ng-model="user.location" ng-options="location.location_cd as location.name for location in locations" class="form-control">
									<option value="">Please select one option</option>
								</select>
							</div>
							<div class="form-group inline-form-grp">
								<label for="location">Gender:</label>
								<select name="gender" ng-model="user.gender" ng-options="gender.id as gender.desc for gender in genders" class="form-control">
									<option value="">Please select one option</option>
								</select>
							</div>
							<div class="form-group inline-form-grp">
								<label for="location">Price Range:</label>
								<select name="range" ng-model="user.range" ng-options="range.id as range.desc for range in ranges" class="form-control">
									<option value="">Please select one option</option>
								</select>
							</div>
							<div class="form-group" style="margin-top:1%;">
								<button type="submit" class="btn" ng-click="SearchPg(user.location,user.gender,user.range)">Search PG</button>
							</div>
						</form>
					</div>
					<div class="tab-pane fade" id="panel-43018" style="margin-top:2%;">
						<div class="col-md-2 col-md-offset-1" ng-repeat="nearbyimage in nearbyimages">
							<a  href rollover class="btn-link" ng-click="select(nearbyimage.id)">
								<figure>
									<img ng-src='/assets/{{nearbyimage.img}}'class="center-block"/>
									<figcaption class="text-center" ng-class="{highlight: isActive(nearbyimage.id)}">{{nearbyimage.name}}</figcaption>
								</figure>
							</a>
						</div>
						<div class="col-md-12" id="restaurant" ng-show="divShow == 1">
							<form class="form-inline text-center" role="form">
								<div class="form-group inline-form-grp">
									<label for="location">Location:</label>
									<select name="location" ng-model="user.location" ng-options="location.location_cd as location.name for location in locations" class="form-control">
									<option value="">Please select one option</option>
								</select>
								</div>
								<div class="form-group inline-form-grp">
									<label for="location">Type of Cuisine</label>
										<select name="cuisine" ng-model="user.cuisine" ng-options="cuisine.id as cuisine.desc for cuisine in cuisines" class="form-control">
											<option value="">Please select one option</option>
										</select>
								</div>
								<div class="form-group inline-form-grp">
									<label for="location">Restaurant Name</label>
									<input type="text" class="form-control"/>
								</div>
								<div class="form-group" style="margin-top:1%;">
									<button type="submit" class="btn">Search Restaurant</button>
								</div>
							</form>
						</div>
						<div class="col-md-12" id="salon" ng-show="divShow == 2">
							<form class="form-inline text-center" role="form">
								<div class="form-group inline-form-grp">
									<label for="location">Location:</label>
									<select name="location" ng-model="user.location" ng-options="location.location_cd as location.name for location in locations" class="form-control">
										<option value="">Please select one option</option>
									</select>
								</div>
								<div class="form-group inline-form-grp">
									<label for="location">Gender:</label>
										<select class="form-control">
											<option>
												Male
											</option>
											<option>
												Female
											</option>
											<option>
												Unisex
											</option>
										</select>
								</div>
								<div class="form-group" style="margin-top:1%;">
									<button type="submit" class="btn">Search Salon</button>
								</div>
							</form>
						</div>
						<div class="col-md-12" id="mall" ng-show="divShow == 3">
							<form class="form-inline text-center" role="form">
								<div class="form-group inline-form-grp">
									<label for="location">Location:</label>
									<select name="location" ng-model="user.location" ng-options="location.location_cd as location.name for location in locations" class="form-control">
										<option value="">Please select one option</option>
									</select>
								</div>
								<div class="form-group" style="margin-top:1%;">
									<button type="submit" class="btn">Search Mall</button>
								</div>
							</form>
						</div>
						<div class="col-md-12" id="gym" ng-show="divShow == 4">
							<form class="form-inline text-center" role="form">
								<div class="form-group inline-form-grp">
									<label for="location">Location:</label>
									<select name="location" ng-model="user.location" ng-options="location.location_cd as location.name for location in locations" class="form-control">
										<option value="">Please select one option</option>
									</select>
								</div>
								<div class="form-group inline-form-grp">
									<label for="location">Gender:</label>
										<select class="form-control">
											<option>
												Male
											</option>
											<option>
												Female
											</option>
											<option>
												Both
											</option>
										</select>
								</div>
								<div class="form-group inline-form-grp">
									<label for="location">Price Range(pm):</label>
									<select name="range" ng-model="user.range" ng-options="range.id as range.desc for range in ranges" class="form-control">
										<option value="">Please select one option</option>
									</select>
								</div>
								<div class="form-group" style="margin-top:1%;">
									<button type="submit" class="btn">Search Gym</button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="clearfix"></div>
<div class="col-md-12 bg-about hideme" id="second_part">
	<div class="col-md-4">
		<h3 class="text-center heading-1">Welcome To PickYourChoice</h3>
	</div>
	<div class="col-md-8">
		<ul class="aboutus">
			<li>Some text about pick your choice.Some text about pick your choice.Some text about pick your choice</li>
			<li>Some text about pick your choice.Some text about pick your choice.Some text about pick your choice</li>
		</ul>
	</div>
</div>
<div class="col-md-12 bg-services hideme" style="padding-top:5%;padding-bottom:5%;">
	<div class="col-md-3">
		Some image to go here
	</div>
	<div class="col-md-8 col-md-offset-1" style="margin-bottom: 30px;">
		<p class="text-center"><%=image_tag 'services_offered_icon.png' %>
		<span style="font-size:22px;">SERVICES OFFERED</span></p>
	  <div class="row">
		<div class="col-md-12" style="margin-top:5%;">
			<div class="col-md-6">
			  <figure class="text-center">	
				  <i class="fa fa-share fa-3x"></i>
				  <figcaption>Post Your Requirement</figcaption>
			  </figure>
			</div>
			<div class="col-md-6">
			  <figure class="text-center">	
				<i class="fa fa-home fa-3x"></i>
				 <figcaption class="text-center">List Your Space</figcaption>
			  </figure>	 
			</div>
		</div>
	  </div>
	  <div class="row clearfix" style="margin-top:8%;">	
		<div class="col-md-12">
			<div class="col-md-6">
			  <figure class="text-center">	
				<i class="fa fa-star fa-3x"></i><i class="fa fa-star-half-full fa-3x"></i><i class="fa fa-star-half fa-3x"></i>
				<figcaption class="text-center">Your Review</figcaption>
			  </figure>
			</div>
			<div class="col-md-6">
			  <figure class="text-center">
				<i class="fa fa-location-arrow fa-3x"></i>
				<figcaption class="text-center">Options Near You</figcaption>
			  </figure>	 
			</div>
		</div>
	  </div>
	</div>
</div>
<div class="col-md-10 col-md-offset-1 hideme">
	<div class="col-md-12">
		<h3>Featured Roofs</h3>
		<div id="owl-featured" class="owl-carousel owl-theme">
			<% @featured_images.each do |h| %>
  			<div class="item">
  				<%=image_tag h.pg_images.url(:medium), :class=>'img-responsive' %>
  			</div>
  			
  			 <% end %>
  		</div>
	</div>
</div>
<!--Navbar ends here-->
<script type="text/javascript">
  var menuOffset = $('#menu')[0].offsetTop;
   $(document).bind('ready scroll', function() {
   var docScroll = $(document).scrollTop();
     if (docScroll >= menuOffset) {
       $('#menu').addClass('fixed');
         } else {
           $('#menu').removeClass('fixed');            
         }
      });

    $("#owl-featured").owlCarousel({
	    navigation: true,
	    navigationText: [
	      "<i class='icon-chevron-left icon-white'></i>",
	      "<i class='icon-chevron-right icon-white'></i>"
	      ],
	});
</script>
<script type="text/javascript">
$(document).ready(function() {
	$(window).scroll( function(){
        $('.hideme').each( function(i){
            var bottom_of_object = $(this).offset().top + $(this).outerHeight();
            var bottom_of_window = $(window).scrollTop() + $(window).height();
            if( bottom_of_window > bottom_of_object ){
                $(this).animate({'opacity':'1'},800);
            }
            
        }); 
	});
});
</script>

app/views/home/phonenum.html.erb
<div class="container" style="margin-top:10%;margin-bottom:5%;">
	<p class="text-center">Please enter your phone number to complete the registration process</p>
	<div class="col-md-6 col-md-offset-3" style="margin-top:1%;margin-bottom:12%;">	
    <%= form_for (@user), url: create_path(@user) ,:class=>"form-horizontal",method: :post do |f|  %>
      <%= f.hidden_field :id, :value => current_user.id %>
      <div class="form-group">
        <%= f.label :PhoneNumber ,:class=>"control-label col-sm-3 "%>
        <div class="col-sm-8">
          <%= f.text_field :phno, autofocus: true, :class => "username-input form-control"%>
        </div>
      </div> 
      <div class="clearfix"></div>
      <div class="form-group text-center" style="margin-top:2%">
          <%= f.submit "Submit", :class => "btn btn-primary" %>
      </div>
    <% end %>
	</div>
</div>