config/routes.rb
  Rails.application.routes.draw do
  get 'gym/index'

  get 'salon/index'

  get 'restaurants/index'

  get 'result/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'home/index'
  
  devise_for :users ,:controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
  get '/users/sign_in' => 'devise/sessions#new'
  get '/users/sign_out' => 'devise/sessions#destroy'
    
end
resources :users  do
  resources :write_review  
  
    member do
      get :following, :followers
    end
  end
resources :featured_images
resources :relationships  
resources :locations , :defaults => {:format => "json"}
get '/location.json' => 'home#index', :defaults => {:format => 'json'}
get '/resultlocation.json' => 'result#index', :defaults => {:format => 'json'}
get '/review.json' => 'result#reviewdetails', :defaults => {:format => 'json'}
get '/userreviews.json' => 'relationships#index', :defaults => {:format => 'json'}
get '/likes.json' => 'result#like', :defaults => {:format => 'json'}
get '/dislikes.json' => 'result#dislike', :defaults => {:format => 'json'}
get '/pgresults.json' => 'result#pgresult', :defaults => {:format => 'json'}
get '/pgresultsbyfood.json' => 'result#pgresultbyfoodtype', :defaults => {:format => 'json'}
get '/restaurantresults.json' => 'restaurants#restaurantresult', :defaults => {:format => 'json'}
get 'relationships/show' 
get '/salonresults.json' => 'salon#salonresult', :defaults => {:format => 'json'}
   root 'home#index'
    post '/create' => 'home#create' 
    

   match '/phonenum' => 'home#phonenum', :via => 'get'
   match '/result' => 'result#index', :via => 'get'
   
   
   get '/review' => 'result#completereview'
   match '/writereview' => 'result#write_review', :via => 'get'
   match '/restaurants' => 'restaurants#index', :via => 'get'
    post '/createreview' => 'result#create' 
    post '/createrestreview' => 'restaurants#create'
    get '/like/:id' => 'result#like' ,as: 'like'
    get '/dislike/:id' => 'result#dislike' ,as: 'dislike'
    post '/createfollower' => 'relationships#create'
    delete '/deletefollower' => 'relationships#destroy'
  match '/followuser' => 'relationships#show', :via => 'get'
  match '/details' => 'detail#details', :via => 'get'
  match '/restaurant_details' => 'restaurant_detail#restaurant_details', :via => 'get'
  match '/salon' => 'salon#index', :via => 'get'
  match '/salon_details' => 'salon_detail#salon_details', :via => 'get'
  match '/gym' => 'gym#index', :via => 'get'
  match '/writerestaurantreview' => 'restaurants#restwritereview', :via => 'get'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="myApp">
<head>
  <title>Pick Your Choice</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body <%= "data-no-turbolinks='true'".html_safe if controller_name=="result" && action_name=="details" %>>
<div class="container-fluid no-padding">
  <div class="row clearfix">
    <div class="col-md-12 column" id="menu">
      <nav class="navbar navbar-default menubar" role="navigation" style="margin-bottom:0;border-radius:0;">
        <div class="navbar-header">
           <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar">
           </span><span class="icon-bar"></span><span class="icon-bar"></span></button>
              <a class="navbar-brand" href="<%=root_path %>" style="background-color: #fff;padding:0;">
                <%=image_tag 'logo.png', :class => 'img-responsive', :style=>'height:53px' %>
              </a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right navigation">
            <li>
              <a href="<%=root_path %>">Home</a>
            </li>
            <li>
              <a href="#">Why PickYourChoice?</a>
            </li>
            <li>
              <a href="#">Services</a>
            </li>
            <li>
              <a href="#">Contact Us</a>
            </li>
            <%  if current_user.present? %>
              <li class="dropdown">
                 <a href="#" class="dropdown-toggle" data-toggle="dropdown">Welcome ! 
                 <%= current_user.username %><strong class="caret"></strong></a>
                <ul class="dropdown-menu">
                  <li>
                    <!-- <a href="#">Edit Profile</a> -->
                    <%= link_to 'Edit Profile', edit_user_registration_path, :method => 'get' %>
                  </li>
                  
                  <li>
                    <a href="#">Notifications (<%= current_user.notifications.count %>)</a>
                  </li>
                  <li>
                    <a href="#">Following (<%= current_user.followeds.count %>)</a>
                  </li>
                  <li>
                    <a href="#">Followers (<%= current_user.followers.count %>)</a>
                  </li>
                  <li>
                    <%= link_to 'logout', destroy_user_session_path, :method => 'get'%>
                  </li>
                </ul>
              </li>
          <% else %>
              <li>
                <a id="modal-469358" href="#modal-container-469358" data-toggle="modal">Login!</a>
              </li>
           <% end %>
            
          </ul>
        </div>
      </nav>
    </div>
  </div>
</div>
<%= yield %>
<div class="col-md-12" style="background-color:#222F37;">
  <div class="container">
    <div class="col-md-12 footer" style="margin-top:3%;">
      <div class="col-md-3 col-sm-4">
        <h5 style="border-bottom:1px solid #fff;color:#fff;">LOCATION</h5>
        <address> <strong>PickYourChoice</strong><br /></address>
      </div>
      <div class="col-md-3 col-sm-4 col-md-offset-1">
        <h5 style="border-bottom:1px solid #fff;color:#fff;">CONTACT</h5>
        <ul class="list-unstyled contact-list">
          <li>PH: 99999-9999</li>
          <li>FAX: 88888-88888</li>
        </ul>
      </div>
      <div class="col-md-3 col-sm-4 col-md-offset-2">
        <h5 style="border-bottom:1px solid #fff;color:#fff;">SOCIAL MEDIA</h5>
        <ul class="list-unstyled list-inline">
          <li><a href="#"><%=image_tag 'fb.png' %></a></li>
          <li><a href="#"><%=image_tag 'tw.png' %></a></li>
        </ul>
      </div>
    </div>
  </div>
  <p class="text-center" style="color:#fff;margin:0;padding-bottom:10px;">All rights reserved @ PickYourChoice</p>
</div>
<div id="error" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">PickYourChoice</h4>
      </div>
      <div class="modal-body" style="margin-left:30px;margin-top:20px;">
        <div id="message"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>
</div>
<div class="modal fade" id="modal-container-469358" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
         
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
          X
        </button>
        <h4 class="modal-title" id="myModalLabel">
          Modal title
        </h4>
      </div>
      <div class="modal-body">
        <div class="login-page">
          <div class="row">
              <div class="col-md-12">
                  <div class="login-form">
                      <div class="login-title">
                        <span class="icon"><i class="glyphicon glyphicon-user"></i></span>
                        <span class="text">Login Area</span>
                      </div><!-- End Title -->
                        <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                          <div class="row">
                              <div class="col-md-6 col-sm-6">
                                  <div class="form-group">
                                  <%= f.email_field :email, :id => "login_username" ,:class => "username-input form-control", :placeholder => "Email", autofocus: true %>
                                  </div>
                              </div>
                             
                              <div class="col-md-6 col-sm-6">
                                  <div class="form-group">
                                    <%= f.password_field :password, :id => "login_password", :class => "password-input form-control", :placeholder => "Password", autocomplete: "off" %>
                                  </div>
                              </div>
                              <div class="col-md-12">
                                  <div class="form-group clearfix">
                                     <%= f.submit "Log in" , :id => "login_submit", :class => "submit-input btn btn-primary center-block"%>
                                  </div>
                              </div>
                              <div class="col-md-6 col-sm-6 clearfix">
                                  <div class="custom-checkbox fl">
                                      <input type="checkbox" id="login_remember" class="checkbox-input" checked="">
                                      <label for="login_remember">Remember Password</label>
                                  </div>
                              </div><!-- end remember -->
                              <div class="col-md-6 col-sm-6 clearfix">
                                  <div class="forgot fr">
                                  <%= link_to "Sign Up", "#modal-container-469359", :id => "modal-469359", "data-toggle" => "modal" %> /
                                   <%= link_to "Forgot your password?", new_password_path(resource_name),:class => "reset" %>
                                  </div>
                              </div><!-- end forgot password -->
                          </div><!-- end row -->
                      <% end %><!-- End form -->
                  </div><!-- end login form -->
                  <div class="login-options">
                      <div class="row">
                          <div class="col-md-6 col-sm-6">
         <%= link_to "Login with Facebook Account", omniauth_authorize_path(resource_name,"facebook") ,:class=>"login-op-btn grad-btn ln-tr fb"%>
                            
                          </div><!-- end FB login -->
                          <div class="col-md-6 col-sm-6">
                            <%= link_to "Login with Google Account", omniauth_authorize_path(resource_name, "google_oauth2"),:class=>"login-op-btn grad-btn ln-tr gp" %>
                              
                          </div><!-- end GP login -->
                      </div>
                  </div><!-- end login optionss -->
              </div><!-- end col-md-12 -->
          </div><!-- end row -->
        </div>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="modal-container-469359" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
         
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
          X
        </button>
        <h4 class="modal-title" id="myModalLabel">
          Modal title
        </h4>
      </div>
      <div class="modal-body">
        <div class="login-page">
          <div class="row">
              <div class="col-md-12">
                  <div class="login-form">
                      <div class="login-title">
                          <span class="icon"><i class="glyphicon glyphicon-user"></i></span>
                          <span class="text">SignUp Area</span>
                      </div><!-- End Title -->
                        <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
                         <%= devise_error_messages! %>
                          <div class="row">
                            <div class="col-md-6 col-sm-6">
                              <div class="form-group">
                              <%= f.email_field :email, :id => "signup_email" ,:class => "username-input form-control", :placeholder => "Email", autofocus: true %>
                              </div>
                            </div>
                             <div class="col-md-6 col-sm-6">
                                  <div class="form-group">
                                    <%= f.text_field :username, :id => "login_name", :class => "password-input form-control", :placeholder => "Username", autocomplete: "off" %>
                                  </div>
                              </div>
                            <div class="col-md-6 col-sm-6">
                              <div class="form-group">
                                <% if @minimum_password_length %>
                                    <em>(<%= @minimum_password_length %> characters minimum)</em>
                                    <% end %>
                                <%= f.password_field :password, :id => "signup_password", :class => "password-input form-control", :placeholder => "Password", autocomplete: "off" %>
                              </div>  
                            </div>
                            <div class="col-md-6 col-sm-6">      
                              <div class="form-group">
                                <%= f.password_field :password_confirmation, :id => "signup_confpassword", :class => "password-input form-control", :placeholder => "Confirm Password", autocomplete: "off" %>
                              </div>
                            </div> 
                            <div class="col-md-6 col-sm-6">      
                              <div class="form-group">
                                <%= f.text_field :phno, :id => "signup_phone", :class => "password-input form-control", :placeholder => "Phone Number", autocomplete: "off" %>
                              </div>
                            </div> 
                            <div class="col-md-12">
                                <div class="form-group clearfix">
                                   <%= f.submit "Sign Up" , :id => "login_submit", :class => "submit-input btn btn-primary center-block"%>
                                </div>
                            </div>
                          </div><!-- end row -->
                      <% end %>
                  </div><!-- end login form -->
              </div><!-- end col-md-12 -->
          </div><!-- end row -->
        </div>
      </div>
    </div>
  </div>
</div>
<script>
    $(document).ready(function() {
        <% if flash[:alert].present? %>
        $("#error").find("#message").html("<%= flash[:alert].html_safe %>");
        $("#error").modal('show');
        <% flash[:alert] = nil %>
        <% end %>

        <% if flash[:notice].present? && flash[:notice] !="You will receive an email with instructions about how to reset your password in a few minutes." %>
        $("#error").find("#message").html("<%= flash[:notice].html_safe %>");
        $("#error").modal('show');
        <% flash[:notice] = nil %>
        <% end %>
    });
</script>
<script type="text/javascript">
  $("#modal-469359").click(function(){
    $("#modal-container-469358").modal('hide');
  });
</script>
</body>
</html>